### ISSUE TITLE
Error :  how to update server information ?.

### ISSUE THREAD

**Issue by vas2201** [ClementiGroup/ExTASY#1]
Hi , 
Thanks for developing this tools and extasy software. I am trying to installing it on our hpc and i am getting the following error.  Could you please suggest me needful to fix the following error ?. 

Looks like i suppose to update my server information in  appmanager.py ?. But I don't know how to do this ?

(extasy) [srp106@gput038 extasy]$ python extasy.py --Kconfig settings/settings_extasy_chignolin_example.wcfg
the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
gput038
set 6 ['module unload python', 'module load python/3.6.6-anaconda3-5.3.0', 'module load cuda/9.1.85', 'module load cmake', 'module load gcc/7.4.0', '. "/sw/summit/python/3.6/anaconda3/5.3.0/etc/profile.d/conda.sh"', 'conda activate', 'conda activate vampextasy6', 'export PATH=/ccs/home/eh22/.conda/envs/vampextasy6/bin:$PATH']
cur_iter 0
copy_arr ['$SHARED/settings_extasy_chignolin_example.wcfg > /gpfs/alpine/proj-shared/bip191/extasy_chignolin_example//settings_extasy_chignolin_example.wcfg', '$SHARED/run-openmm7.py > /gpfs/alpine/proj-shared/bip191/extasy_chignolin_example//run-openmm7.py', '$SHARED/chignolin-ca-crystal.pdb > /gpfs/alpine/proj-shared/bip191/extasy_chignolin_example//chignolin-ca-crystal.pdb', '$SHARED/run-vamp3.py > /gpfs/alpine/proj-shared/bip191/extasy_chignolin_example//run-vamp3.py']
finished prep
u 0 1 5 6 1 0 0
u 0 1 5 6 1 1 1
u 0 1 5 6 1 2 2
u 0 1 5 6 1 3 3
u 0 1 5 6 1 4 4
analysis task 0
using gpus
{'resource': 'ornl.summit', 'walltime': 10, 'cpus': 22, 'gpus': 6, 'project': 'BIP191', 'queue': 'batch', 'schema': 'local'}
shared_data_all ['settings/settings_extasy_chignolin_example.wcfg', './files-chignolin//system-5.xml', './files-chignolin//integrator-5.xml', './files-chignolin/chignolin-ca-crystal.pdb', './helper_scripts/run-openmm7.py', './files-chignolin/chignolin.pdb', './helper_scripts/run-vamp3.py']
EnTK session: re.session.gput038.srp106.019387.0008
Creating AppManagerSetting up RabbitMQ system                                 ok
Error: (-1, "ConnectionResetError(104, 'Connection reset by peer')")
Traceback (most recent call last):
  File "/home/srp106/miniconda3/envs/extasy/lib/python3.9/site-packages/radical/entk/appman/appmanager.py", line 567, in _setup_mqs
    mq_connection = pika.BlockingConnection(self._rmq_conn_params)
  File "/home/srp106/miniconda3/envs/extasy/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 377, in __init__
    self._process_io_for_connection_setup()
  File "/home/srp106/miniconda3/envs/extasy/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 416, in _process_io_for_connection_setup
    self._flush_output(self._opened_result.is_ready,
  File "/home/srp106/miniconda3/envs/extasy/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 469, in _flush_output
    raise maybe_exception
pika.exceptions.IncompatibleProtocolError: (-1, "ConnectionResetError(104, 'Connection reset by peer')")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/srp106/projects/extasy/extasy.py", line 270, in <module>
    appman = AppManager(hostname='gput038', port=6818)
  File "/home/srp106/miniconda3/envs/extasy/lib/python3.9/site-packages/radical/entk/appman/appmanager.py", line 134, in __init__
    self._setup_mqs()
  File "/home/srp106/miniconda3/envs/extasy/lib/python3.9/site-packages/radical/entk/appman/appmanager.py", line 601, in _setup_mqs
    raise ree.EnTKError(ex) from ex
radical.entk.exceptions.EnTKError: (-1, "ConnectionResetError(104, 'Connection reset by peer')")

Regards
Vas

**Comment by euhruska** [comment]
In file settings/settings_extasy_chignolin_example.wcfg update parameters REMOTE_HOST, ALLOCATION, remote_output_directory, md_env, ana_env. General information for setting RabbitMQ: https://radicalentk.readthedocs.io/en/latest/install.html#rabbitmq for setting REMOTE_HOST: https://radicalentk.readthedocs.io/en/latest/user_guide/change_target.html
